FROM node:22-alpine AS builder
WORKDIR /app

COPY package*.json ./
COPY shared ./shared
COPY frontend ./frontend

WORKDIR /app/frontend
RUN npm ci
RUN npm run build

FROM nginx:1.27-alpine AS runner
COPY --from=builder /app/frontend/dist /usr/share/nginx/html
COPY frontend/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
